# Generated by Django 6.0.1 on 2026-04-02 22:23

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
import multiselectfield.db.fields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='CoachAvailability',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.DateTimeField()),
                ('end_time', models.DateTimeField()),
                ('is_booked', models.BooleanField(default=False)),
                ('is_recurring', models.BooleanField(default=False, help_text='If True, this slot repeats weekly')),
                ('recurrence_group', models.UUIDField(blank=True, help_text='UUID to group recurring slots (all slots in a series share the same UUID)', null=True)),
            ],
            options={
                'verbose_name_plural': 'Coach availabilities',
                'ordering': ['start_time'],
            },
        ),
        migrations.CreateModel(
            name='ContactMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('subject', models.CharField(max_length=250)),
                ('message', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_read', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='EquipmentList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=25, unique=True)),
                ('description', models.TextField(blank=True, help_text='Add description here')),
                ('quantity', models.PositiveIntegerField(default=1, help_text='Number of units available')),
                ('is_active', models.BooleanField(default=True, help_text='Uncheck when out of service')),
            ],
            options={
                'verbose_name_plural': 'Equipments',
            },
        ),
        migrations.CreateModel(
            name='GymInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.IntegerField(choices=[(0, 'Monday'), (1, 'Tuesday'), (2, 'Wednesday'), (3, 'Thursday'), (4, 'Friday'), (5, 'Saturday'), (6, 'Sunday')], unique=True)),
                ('open_time', models.TimeField(blank=True, help_text='Opening time (leave blank if closed)', null=True)),
                ('close_time', models.TimeField(blank=True, help_text='Closing time (leave blank if closed)', null=True)),
                ('is_open', models.BooleanField(default=True, help_text='Uncheck to mark the gym closed all day')),
                ('is_open_24h', models.BooleanField(default=False, help_text='Check if the gym is open 24 hours on this day')),
            ],
            options={
                'verbose_name_plural': 'Gym Information',
                'ordering': ['day'],
            },
        ),
        migrations.CreateModel(
            name='Recipe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.CharField(help_text='Brief summary of the recipe', max_length=250)),
                ('locked', models.BooleanField(default=False, help_text='Premium content — requires login to view')),
                ('prep_time_minutes', models.PositiveIntegerField(help_text='Preparation time in minutes')),
                ('cook_time_minutes', models.PositiveIntegerField(help_text='Cooking time in minutes (0 if none)')),
                ('servings', models.PositiveIntegerField(default=1)),
                ('difficulty', models.CharField(choices=[('EASY', 'Easy'), ('MEDIUM', 'Medium'), ('HARD', 'Hard')], default='MEDIUM', max_length=10)),
                ('instructions', models.TextField(help_text='Step-by-step cooking instructions')),
                ('calories_per_serving', models.PositiveIntegerField(blank=True, help_text='Approximate calories per serving (optional)', null=True)),
                ('dietary_restrictions', multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('NO_NUTS', 'No Nuts'), ('NO_SEAFOOD', 'No Seafood'), ('NO_DAIRY_LACTOSE', 'No Dairy Lactose'), ('NO_RED_MEAT', 'No Red Meat'), ('NO_PORK', 'No Pork'), ('NO_ALCOHOL', 'No Alcohol'), ('NO_SHELLFISH', 'No Shellfish'), ('NO_GLUTEN', 'No Gluten'), ('NO_SESAME', 'No Sesame'), ('NO_MUSTARD', 'No Mustard'), ('VEGAN', 'Vegan'), ('VEGETARIAN', 'Vegetarian')], help_text='Dietary choices (optional)', max_length=250)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='WorkoutPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('locked', models.BooleanField(default=False, help_text='Premium content — requires login to view')),
                ('description', models.CharField(help_text='Brief summary of the workout plan', max_length=100)),
                ('body', models.TextField(help_text='Detailed overview of the plan')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('difficulty', models.CharField(choices=[('EASY', 'Easy'), ('MEDIUM', 'Medium'), ('HARD', 'Hard')], default='MEDIUM', max_length=10)),
                ('duration_minutes', models.PositiveIntegerField(default=0)),
                ('goal', models.CharField(choices=[('', ''), ('STRENGTH', 'Strength'), ('CARDIO', 'Cardio'), ('FLEXIBILITY', 'Flexible'), ('WEIGHT_LOSS', 'Weight Loss'), ('MUSCLE_GAIN', 'Muscle Gain')], default='', max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='CoachAppointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.DateTimeField()),
                ('end_time', models.DateTimeField()),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('ACCEPTED', 'Accepted'), ('REFUSED', 'Refused'), ('CANCELLED', 'Cancelled')], default='PENDING', max_length=20)),
                ('refusal_reason', models.TextField(blank=True, help_text='Reason if refused')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('availability', models.OneToOneField(blank=True, help_text='Linked availability slot', null=True, on_delete=django.db.models.deletion.SET_NULL, to='CUFitness.coachavailability')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Exercise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.CharField(help_text='Brief summary of the exercise', max_length=250)),
                ('instructions', models.TextField(help_text='Step-by-step instructions')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('muscle_group', models.CharField(blank=True, choices=[('CHEST', 'Chest'), ('BACK', 'Back'), ('LEGS', 'Legs'), ('SHOULDERS', 'Shoulders'), ('ARMS', 'Arms'), ('CORE', 'Core'), ('FULL_BODY', 'Full Body')], max_length=30, null=True)),
                ('difficulty', models.CharField(blank=True, choices=[('EASY', 'Easy'), ('MEDIUM', 'Medium'), ('HARD', 'Hard')], max_length=25, null=True)),
                ('goal', models.CharField(choices=[('', ''), ('STRENGTH', 'Strength'), ('CARDIO', 'Cardio'), ('FLEXIBILITY', 'Flexible'), ('WEIGHT_LOSS', 'Weight Loss'), ('MUSCLE_GAIN', 'Muscle Gain')], default='', max_length=15)),
                ('equipment', models.ManyToManyField(blank=True, related_name='exercises', to='CUFitness.equipmentlist')),
            ],
        ),
        migrations.CreateModel(
            name='RecipeIngredient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('quantity', models.DecimalField(decimal_places=2, help_text='e.g. 1.5, 100, 0.25', max_digits=7)),
                ('unit', models.CharField(choices=[('TSP', 'tsp'), ('TBSP', 'tbsp'), ('CUP', 'cup'), ('ML', 'ml'), ('L', 'l'), ('FL_OZ', 'fl oz'), ('G', 'g'), ('KG', 'kg'), ('OZ', 'oz'), ('LB', 'lb'), ('WHOLE', 'whole'), ('PINCH', 'pinch'), ('SLICE', 'slice'), ('OTHER', 'other')], default='OTHER', max_length=10)),
                ('unit_other', models.CharField(blank=True, help_text='Describe unit if "other" selected', max_length=50)),
                ('notes', models.CharField(blank=True, help_text='e.g. "finely chopped", "optional"', max_length=100)),
                ('recipe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ingredients', to='CUFitness.recipe')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='WorkoutPlanExercise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sets', models.PositiveIntegerField(default=0)),
                ('reps', models.CharField(default='0', help_text='e.g. "10" or "8-12"', max_length=20)),
                ('rest_seconds', models.PositiveIntegerField(default=60)),
                ('order', models.PositiveIntegerField(default=0)),
                ('notes', models.CharField(blank=True, max_length=100)),
                ('exercise', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='workout_plans', to='CUFitness.exercise')),
                ('workout', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exercises', to='CUFitness.workoutplan')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='CustomUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('role', models.CharField(choices=[('MEMBER', 'Member'), ('COACH', 'Coach'), ('STAFF', 'Staff'), ('ADMIN', 'Admin')], default='MEMBER', max_length=20, verbose_name='user role')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='email address')),
                ('first_name', models.CharField(default='', max_length=50, verbose_name='first name')),
                ('last_name', models.CharField(default='', max_length=50, verbose_name='last name')),
                ('membership', models.CharField(choices=[('BASIC', 'Basic'), ('STANDARD', 'Standard'), ('PLATINUM', 'Platinum'), ('PER_SESSION', 'Per Session')], default='BASIC', max_length=50, verbose_name='membership')),
                ('phone_number', models.CharField(default='', help_text='e.g. +1 514 555 0123', max_length=20)),
                ('date_of_birth', models.DateField(help_text='Format: YYYY-MM-DD', null=True)),
                ('address', models.CharField(blank=True, default='', help_text='Address here', max_length=255)),
                ('profile_picture', models.ImageField(blank=True, default='defaults/Default_Profile_Picture.jpg', upload_to='profile_pictures/')),
                ('coach_request_status', models.CharField(choices=[('NONE', 'No Request'), ('PENDING', 'Pending Approval'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected')], default='NONE', max_length=20, verbose_name='Coach request status')),
                ('workout_visibility', models.CharField(choices=[('PUBLIC', 'Public'), ('COACH_ONLY', 'Coach Only')], default='COACH_ONLY', max_length=20, verbose_name='Workout history privacy setting')),
                ('is_staff', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'permissions': [('can_ban_users', 'Can ban users'), ('can_view_coach_requests', 'Can view coach requests'), ('can_accept_coach_requests', 'Can accept coach requests'), ('can_change_user_role', 'Can change user role'), ('can_view_user_reports', 'Can view user reports')],
            },
        ),
        migrations.AddField(
            model_name='workoutplan',
            name='author',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='workouts', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='recipe',
            name='author',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recipes', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=200)),
                ('body', models.TextField(max_length=3000)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('is_read', models.BooleanField(default=False)),
                ('recipient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='received_messages', to=settings.AUTH_USER_MODEL)),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sent_messages', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
        migrations.AddField(
            model_name='exercise',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exercises', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='CoachReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.PositiveSmallIntegerField(help_text='Rating from 1 to 5 stars', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('comment', models.TextField(blank=True, help_text='Optional comment (max 500 characters)', max_length=500)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('appointment', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='review', to='CUFitness.coachappointment')),
                ('coach', models.ForeignKey(limit_choices_to={'role': 'COACH'}, on_delete=django.db.models.deletion.CASCADE, related_name='received_reviews', to=settings.AUTH_USER_MODEL)),
                ('member', models.ForeignKey(limit_choices_to={'role': 'MEMBER'}, on_delete=django.db.models.deletion.CASCADE, related_name='written_reviews', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Coach Review',
                'verbose_name_plural': 'Coach Reviews',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='coachavailability',
            name='coach',
            field=models.ForeignKey(limit_choices_to={'role': 'COACH'}, on_delete=django.db.models.deletion.CASCADE, related_name='availabilities', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='coachappointment',
            name='coach',
            field=models.ForeignKey(limit_choices_to={'role': 'COACH'}, on_delete=django.db.models.deletion.CASCADE, related_name='coach_appointments', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='coachappointment',
            name='member',
            field=models.ForeignKey(limit_choices_to={'role': 'MEMBER'}, on_delete=django.db.models.deletion.CASCADE, related_name='member_appointments', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='Challenge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('description', models.TextField()),
                ('goal_target', models.IntegerField()),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('locked', models.BooleanField(default=False, help_text='Premium content — requires login to view')),
                ('description', models.CharField(help_text='Brief summary of the article', max_length=250)),
                ('body', models.TextField(help_text='Add body here')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('author', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='articles', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ChallengeParticipation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('progress', models.IntegerField(default=0)),
                ('joined_at', models.DateTimeField(auto_now_add=True)),
                ('challenge', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CUFitness.challenge')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'challenge')},
            },
        ),
    ]
