# Generated by Django 6.0.1 on 2026-03-09 15:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CUFitness', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coachappointment',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('ACCEPTED', 'Accepted'), ('REFUSED', 'Refused'), ('CANCELLED', 'Cancelled')], default='PENDING', max_length=20),
        ),
        migrations.AlterField(
            model_name='equipmentbooking',
            name='coach',
            field=models.ForeignKey(limit_choices_to={'role': 'COACH'}, on_delete=django.db.models.deletion.CASCADE, related_name='coached_bookings', to=settings.AUTH_USER_MODEL),
        ),
    ]
