# Generated by Django 6.0.1 on 2026-03-01 02:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CUFitness', '0002_customuser_first_name_customuser_last_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='membership',
            field=models.CharField(blank=True, choices=[('BASIC', 'Basic'), ('STANDARD', 'Standard'), ('PLATINUM', 'Platinum'), ('PER SESSION', 'Per Session')], max_length=50, null=True, verbose_name='membership'),
        ),
    ]
