# Generated by Django 6.0.1 on 2026-04-07 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CUFitness', '0002_alter_customuser_address_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workoutplan',
            name='description',
            field=models.CharField(help_text='Brief summary of the workout plan', max_length=250),
        ),
    ]
