# Generated by Django 6.0.1 on 2026-03-09 16:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('CUFitness', '0002_alter_coachappointment_status_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Articles',
            new_name='Article',
        ),
    ]
