# Generated by Django 5.2.11 on 2026-03-02 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CUFitness', '0003_customuser_membership'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('member', 'Member'), ('coach', 'Coach'), ('staff', 'Staff'), ('admin', 'Admin')], default='member', max_length=20, verbose_name='user role'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='membership',
            field=models.CharField(choices=[('BASIC', 'Basic'), ('STANDARD', 'Standard'), ('PLATINUM', 'Platinum'), ('PER SESSION', 'Per Session')], default='BASIC', max_length=50, verbose_name='membership'),
        ),
    ]
