# Generated by Django 6.0.1 on 2026-03-03 22:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('CUFitness', '0005_equipmentlist_customuser_coach_request_status_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customuser',
            options={'permissions': [('can_login_as_staff', 'Can login as Staff')]},
        ),
    ]
