# Generated by Django 6.0.1 on 2026-03-09 22:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CUFitness', '0005_alter_article_author'),
    ]

    operations = [
        migrations.CreateModel(
            name='Recipe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.CharField(help_text='Brief summary of the recipe', max_length=250)),
                ('locked', models.BooleanField(default=False, help_text='Premium content — requires login to view')),
                ('prep_time_minutes', models.PositiveIntegerField(help_text='Preparation time in minutes')),
                ('cook_time_minutes', models.PositiveIntegerField(help_text='Cooking time in minutes (0 if none)')),
                ('servings', models.PositiveIntegerField(default=1)),
                ('difficulty', models.CharField(choices=[('EASY', 'Easy'), ('MEDIUM', 'Medium'), ('HARD', 'Hard')], default='MEDIUM', max_length=10)),
                ('instructions', models.TextField(help_text='Step-by-step cooking instructions')),
                ('calories_per_serving', models.PositiveIntegerField(blank=True, help_text='Approximate calories per serving (optional)', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('author', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recipes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='RecipeIngredient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('quantity', models.CharField(help_text='e.g. "2 cups", "100g", "1 tbsp"', max_length=50)),
                ('notes', models.CharField(blank=True, help_text='e.g. "finely chopped", "optional"', max_length=100)),
                ('recipe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ingredients', to='CUFitness.recipe')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
    ]
