# Generated by Django 6.0.1 on 2026-03-10 16:49

import multiselectfield.db.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CUFitness', '0006_recipe_recipeingredient'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='dietary_choices',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('NO_NUTS', 'No Nuts'), ('NO_SEAFOOD', 'No Seafood'), ('NO_DAIRY_LACTOSE', 'No Dairy Lactose'), ('NO_RED_MEET', 'No Red Meet'), ('NO_PORK', 'No Pork'), ('NO_ALCOHOL', 'No Alcohol'), ('NO_SHELLFISH', 'No Shellfish'), ('NO_GLUTEN', 'No Gluten'), ('NO_SESAME', 'No Sesame'), ('NO_MUSTARD', 'No Mustard'), ('VEGAN', 'Vegan'), ('VEGETARIAN', 'Vegetarian')], help_text='Dietary choices (optional)', max_length=127, null=True),
        ),
        migrations.AlterField(
            model_name='article',
            name='description',
            field=models.CharField(help_text='Brief summary of the recipe', max_length=250),
        ),
        migrations.AlterField(
            model_name='article',
            name='locked',
            field=models.BooleanField(default=False, help_text='Premium content — requires login to view'),
        ),
        migrations.AlterField(
            model_name='article',
            name='title',
            field=models.CharField(max_length=100),
        ),
    ]
