# Generated by Django 6.0.1 on 2026-03-03 22:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('CUFitness', '0006_alter_customuser_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customuser',
            options={'permissions': [('can_ban_users', 'Can ban users'), ('can_view_coach_requests', 'Can view coach requests'), ('can_accept_coach_requests', 'Can accept coach requests'), ('can_change_user_role', 'Can change user role')]},
        ),
    ]
