# Generated by Django 6.0.1 on 2026-03-10 17:05

import multiselectfield.db.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CUFitness', '0007_recipe_dietary_choices_alter_article_description_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recipe',
            name='dietary_choices',
        ),
        migrations.AddField(
            model_name='recipe',
            name='dietary_restrictions',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('NO_NUTS', 'No Nuts'), ('NO_SEAFOOD', 'No Seafood'), ('NO_DAIRY_LACTOSE', 'No Dairy Lactose'), ('NO_RED_MEAT', 'No Red Meat'), ('NO_PORK', 'No Pork'), ('NO_ALCOHOL', 'No Alcohol'), ('NO_SHELLFISH', 'No Shellfish'), ('NO_GLUTEN', 'No Gluten'), ('NO_SESAME', 'No Sesame'), ('NO_MUSTARD', 'No Mustard'), ('VEGAN', 'Vegan'), ('VEGETARIAN', 'Vegetarian')], help_text='Dietary choices (optional)', max_length=250),
        ),
        migrations.AddField(
            model_name='recipeingredient',
            name='unit',
            field=models.CharField(choices=[('TSP', 'tsp'), ('TBSP', 'tbsp'), ('CUP', 'cup'), ('ML', 'ml'), ('L', 'l'), ('FL_OZ', 'fl oz'), ('G', 'g'), ('KG', 'kg'), ('OZ', 'oz'), ('LB', 'lb'), ('WHOLE', 'whole'), ('PINCH', 'pinch'), ('SLICE', 'slice'), ('OTHER', 'other')], default='OTHER', max_length=10),
        ),
        migrations.AddField(
            model_name='recipeingredient',
            name='unit_other',
            field=models.CharField(blank=True, help_text='Describe unit if "other" selected', max_length=50),
        ),
        migrations.AlterField(
            model_name='recipeingredient',
            name='quantity',
            field=models.DecimalField(decimal_places=2, help_text='e.g. 1.5, 100, 0.25', max_digits=7),
        ),
    ]
