# Generated by Django 6.0.1 on 2026-03-11 23:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CUFitness', '0008_remove_recipe_dietary_choices_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='description',
            field=models.CharField(help_text='Brief summary of the article', max_length=250),
        ),
        migrations.CreateModel(
            name='Exercise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.CharField(help_text='Brief summary of the exercise', max_length=250)),
                ('instructions', models.TextField(help_text='Step-by-step instructions')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('muscle_group', models.CharField(blank=True, choices=[('CHEST', 'Chest'), ('BACK', 'Back'), ('LEGS', 'Legs'), ('SHOULDERS', 'Shoulders'), ('ARMS', 'Arms'), ('CORE', 'Core'), ('FULL_BODY', 'Full Body')], max_length=30, null=True)),
                ('difficulty', models.CharField(blank=True, choices=[('EASY', 'Easy'), ('MEDIUM', 'Medium'), ('HARD', 'Hard')], max_length=25, null=True)),
                ('goal', models.CharField(choices=[('STRENGTH', 'Strength'), ('CARDIO', 'Cardio'), ('FLEXIBILITY', 'Flexible'), ('WEIGHT_LOSS', 'Weight Loss'), ('MUSCLE_GAIN', 'Muscle Gain')], default='', max_length=15)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exercises', to=settings.AUTH_USER_MODEL)),
                ('equipment', models.ManyToManyField(blank=True, related_name='exercises', to='CUFitness.equipmentlist')),
            ],
        ),
        migrations.CreateModel(
            name='WorkoutPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('locked', models.BooleanField(default=False, help_text='Premium content — requires login to view')),
                ('description', models.CharField(help_text='Brief summary of the workout plan', max_length=100)),
                ('body', models.TextField(help_text='Detailed overview of the plan')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('difficulty', models.CharField(choices=[('EASY', 'Easy'), ('MEDIUM', 'Medium'), ('HARD', 'Hard')], default='MEDIUM', max_length=10)),
                ('duration_minutes', models.PositiveIntegerField(default=0)),
                ('goal', models.CharField(choices=[('STRENGTH', 'Strength'), ('CARDIO', 'Cardio'), ('FLEXIBILITY', 'Flexible'), ('WEIGHT_LOSS', 'Weight Loss'), ('MUSCLE_GAIN', 'Muscle Gain')], default='', max_length=15)),
                ('author', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='workouts', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='WorkoutPlanExercise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sets', models.PositiveIntegerField(default=0)),
                ('reps', models.CharField(default='0', help_text='e.g. "10" or "8-12"', max_length=20)),
                ('rest_seconds', models.PositiveIntegerField(default=60)),
                ('order', models.PositiveIntegerField(default=0)),
                ('notes', models.CharField(blank=True, max_length=100)),
                ('exercise', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='workout_plans', to='CUFitness.exercise')),
                ('workout', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exercises', to='CUFitness.workoutplan')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
    ]
