# Generated by Django 6.0.1 on 2026-03-04 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CUFitness', '0008_alter_customuser_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='coach_request_status',
            field=models.CharField(choices=[('NONE', 'No Request'), ('PENDING', 'Pending Approval'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected')], default='none', max_length=20, verbose_name='Coach request status'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='membership',
            field=models.CharField(choices=[('BASIC', 'Basic'), ('STANDARD', 'Standard'), ('PLATINUM', 'Platinum'), ('PER_SESSION', 'Per Session')], default='BASIC', max_length=50, verbose_name='membership'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('MEMBER', 'Member'), ('COACH', 'Coach'), ('STAFF', 'Staff'), ('ADMIN', 'Admin')], default='MEMBER', max_length=20, verbose_name='user role'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='workout_visibility',
            field=models.CharField(choices=[('PUBLIC', 'Public'), ('COACH_ONLY', 'Coach Only')], default='COACH_ONLY', max_length=20, verbose_name='Workout history privacy setting'),
        ),
    ]
