# Generated by Django 6.0.1 on 2026-03-04 18:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CUFitness', '0009_alter_customuser_coach_request_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coachappointment',
            name='coach',
            field=models.ForeignKey(limit_choices_to={'role': 'COACH'}, on_delete=django.db.models.deletion.CASCADE, related_name='coach_appointments', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='coachappointment',
            name='member',
            field=models.ForeignKey(limit_choices_to={'role': 'MEMBER'}, on_delete=django.db.models.deletion.CASCADE, related_name='member_appointments', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='coachavailability',
            name='coach',
            field=models.ForeignKey(limit_choices_to={'role': 'COACH'}, on_delete=django.db.models.deletion.CASCADE, related_name='availabilities', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='equipment_booking',
            name='coach',
            field=models.ForeignKey(limit_choices_to={'role': 'COACH'}, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
