# Generated by Django 6.0.1 on 2026-03-14 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CUFitness', '0009_alter_article_description_exercise_workoutplan_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exercise',
            name='goal',
            field=models.CharField(choices=[('', ''), ('STRENGTH', 'Strength'), ('CARDIO', 'Cardio'), ('FLEXIBILITY', 'Flexible'), ('WEIGHT_LOSS', 'Weight Loss'), ('MUSCLE_GAIN', 'Muscle Gain')], default='', max_length=15),
        ),
        migrations.AlterField(
            model_name='workoutplan',
            name='goal',
            field=models.CharField(choices=[('', ''), ('STRENGTH', 'Strength'), ('CARDIO', 'Cardio'), ('FLEXIBILITY', 'Flexible'), ('WEIGHT_LOSS', 'Weight Loss'), ('MUSCLE_GAIN', 'Muscle Gain')], default='', max_length=15),
        ),
    ]
