# Generated by Django 6.0.1 on 2026-03-04 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CUFitness', '0010_alter_coachappointment_coach_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='coach_request_status',
            field=models.CharField(choices=[('NONE', 'No Request'), ('PENDING', 'Pending Approval'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected')], default='NONE', max_length=20, verbose_name='Coach request status'),
        ),
    ]
