# Generated by Django 6.0.1 on 2026-03-14 23:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CUFitness', '0010_alter_exercise_goal_alter_workoutplan_goal'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='address',
            field=models.CharField(blank=True, default='', help_text='Address here', max_length=255),
        ),
        migrations.AddField(
            model_name='customuser',
            name='date_of_birth',
            field=models.DateField(help_text='Format: YYYY-MM-DD', null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='phone_number',
            field=models.CharField(default='', help_text='e.g. +1 514 555 0123', max_length=20),
        ),
    ]
