# Generated by Django 6.0.1 on 2026-03-16 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CUFitness', '0011_customuser_address_customuser_date_of_birth_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='GymInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.IntegerField(choices=[(0, 'Monday'), (1, 'Tuesday'), (2, 'Wednesday'), (3, 'Thursday'), (4, 'Friday'), (5, 'Saturday'), (6, 'Sunday')], unique=True)),
                ('open_time', models.TimeField(blank=True, help_text='Opening time (leave blank if closed)', null=True)),
                ('close_time', models.TimeField(blank=True, help_text='Closing time (leave blank if closed)', null=True)),
                ('is_open', models.BooleanField(default=True, help_text='Uncheck to mark the gym closed all day')),
            ],
            options={
                'verbose_name_plural': 'Gym settings',
                'ordering': ['day'],
            },
        ),
        migrations.AddField(
            model_name='coachavailability',
            name='is_recurring',
            field=models.BooleanField(default=False, help_text='If True, this slot repeats weekly'),
        ),
        migrations.AddField(
            model_name='coachavailability',
            name='recurrence_group',
            field=models.UUIDField(blank=True, help_text='UUID to group recurring slots (all slots in a series share the same UUID)', null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='auto_accept_appointments',
            field=models.BooleanField(default=False, help_text='Automatically accept all incoming appointment requests'),
        ),
    ]
