# Generated by Django 6.0.1 on 2026-03-05 17:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('CUFitness', '0012_articles'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='articles',
            name='body',
        ),
    ]
