# Generated by Django 6.0.1 on 2026-03-05 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CUFitness', '0013_remove_articles_body'),
    ]

    operations = [
        migrations.AddField(
            model_name='articles',
            name='locked',
            field=models.BooleanField(default=False),
        ),
    ]
