# Generated by Django 6.0.1 on 2026-03-16 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CUFitness', '0013_message'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='equipmentbooking',
            name='unique_booking_per_timeslot',
        ),
        migrations.AlterModelOptions(
            name='gyminfo',
            options={'ordering': ['day'], 'verbose_name_plural': 'Gym Information'},
        ),
        migrations.AddField(
            model_name='equipmentlist',
            name='quantity',
            field=models.PositiveIntegerField(default=1, help_text='Number of units available'),
        ),
        migrations.DeleteModel(
            name='EquipmentBooking',
        ),
    ]
