# Generated by Django 6.0.1 on 2026-03-05 17:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('CUFitness', '0014_articles_locked'),
    ]

    operations = [
        migrations.RenameField(
            model_name='articles',
            old_name='description',
            new_name='body',
        ),
    ]
