# Generated by Django 6.0.1 on 2026-03-29 20:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CUFitness', '0014_remove_equipmentbooking_unique_booking_per_timeslot_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='profile_picture',
            field=models.ImageField(blank=True, default='defaults/Default_Profile_Picture.jpg', upload_to='profile_pictures/'),
        ),
    ]
