# Generated by Django 6.0.1 on 2026-03-30 00:06

from django.conf import settings
from django.db import migrations, models
import django.core.validators
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('CUFitness', '0014_remove_equipmentbooking_unique_booking_per_timeslot_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CoachReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.PositiveSmallIntegerField(
                    validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)],
                    help_text='Rating from 1 to 5'
                )),
                ('body', models.TextField(max_length=1000, help_text='Your review')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('appointment', models.OneToOneField(
                    on_delete=django.db.models.deletion.CASCADE,
                    related_name='review',
                    to='CUFitness.coachappointment'
                )),
                ('coach', models.ForeignKey(
                    limit_choices_to={'role': 'COACH'},
                    on_delete=django.db.models.deletion.CASCADE,
                    related_name='reviews',
                    to=settings.AUTH_USER_MODEL
                )),
                ('member', models.ForeignKey(
                    limit_choices_to={'role': 'MEMBER'},
                    on_delete=django.db.models.deletion.CASCADE,
                    related_name='given_reviews',
                    to=settings.AUTH_USER_MODEL
                )),
            ],
            options={'ordering': ['-created_at']},
        ),
    ]
