# Generated by Django 6.0.1 on 2026-03-05 20:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CUFitness', '0015_rename_description_articles_body'),
    ]

    operations = [
        migrations.AddField(
            model_name='articles',
            name='description',
            field=models.TextField(blank=True, help_text='Add description here'),
        ),
    ]
