# Generated by Django 6.0.1 on 2026-03-30 22:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CUFitness', '0015_customuser_profile_picture'),
    ]

    operations = [
        migrations.AddField(
            model_name='equipmentlist',
            name='maintenance_end',
            field=models.DateField(blank=True, help_text='Expected return date', null=True),
        ),
        migrations.AddField(
            model_name='equipmentlist',
            name='maintenance_note',
            field=models.CharField(blank=True, help_text='Reason for maintenance', max_length=200),
        ),
        migrations.AddField(
            model_name='equipmentlist',
            name='maintenance_start',
            field=models.DateField(blank=True, help_text='Start of maintenance period', null=True),
        ),
    ]
