# Generated by Django 6.0.1 on 2026-03-05 20:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CUFitness', '0016_articles_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articles',
            name='description',
            field=models.CharField(help_text='Add description here', max_length=250),
        ),
    ]
