# Generated by Django 6.0.1 on 2026-03-31 00:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('CUFitness', '0015_customuser_profile_picture'),
        ('CUFitness', '0016_challenge_created_at'),
    ]

    operations = [
    ]
