# Generated by Django 6.0.1 on 2026-03-06 00:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('CUFitness', '0017_alter_articles_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='articles',
            name='user',
        ),
    ]
