# Generated by Django 6.0.1 on 2026-04-02 18:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('CUFitness', '0018_coachreview'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='auto_accept_appointments',
        ),
    ]
