# Generated by Django 6.0.1 on 2026-04-01 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CUFitness', '0018_contactmessage_alter_customuser_address_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='gyminfo',
            name='is_open_24h',
            field=models.BooleanField(default=False, help_text='Check if the gym is open 24 hours on this day'),
        ),
    ]
