# Generated by Django 6.0.1 on 2026-04-01 15:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('CUFitness', '0019_gyminfo_is_open_24h'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='exercise',
            name='created_by',
        ),
    ]
