# Generated by Django 6.0.1 on 2026-04-02 19:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CUFitness', '0019_remove_customuser_auto_accept_appointments'),
    ]

    operations = [
        migrations.AddField(
            model_name='workoutplan',
            name='appointment',
            field=models.ForeignKey(blank=True, help_text='Appointment this workout plan is created for', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='workout_plans', to='CUFitness.coachappointment'),
        ),
    ]
