# Generated by Django 6.0.1 on 2026-03-06 00:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CUFitness', '0020_alter_articles_author'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articles',
            name='body',
            field=models.TextField(help_text='Add body here'),
        ),
    ]
